In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
loans_df = pd.read_csv('loan_status.csv')
loans_df.head()
# 36,422 Rows    17 Columns

,Loan_Status,Current_Loan_Amount,Term,Credit_Score,Annual_Income,Years_in_current_job,Home_Ownership,Purpose,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,Bankruptcies,Tax_Liens
0,Fully_Paid,99999999,Short_Term,741.0,2231892.0,8_years,Own_Home,Debt_Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
1,Fully_Paid,217646,Short_Term,730.0,1184194.0,<_1_year,Home_Mortgage,Debt_Consolidation,10855.08,19.6,10.0,13,1,122170,272052.0,1.0,0.0
2,Fully_Paid,548746,Short_Term,678.0,2559110.0,2_years,Rent,Debt_Consolidation,18660.28,22.6,33.0,4,0,437171,555038.0,0.0,0.0
3,Fully_Paid,99999999,Short_Term,728.0,714628.0,3_years,Rent,Debt_Consolidation,11851.06,16.0,76.0,16,0,203965,289784.0,0.0,0.0
4,Fully_Paid,99999999,Short_Term,740.0,776188.0,<_1_year,Own_Home,Debt_Consolidation,11578.22,8.5,25.0,6,0,134083,220220.0,0.0,0.0

In [3]:
loans_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36423 entries, 0 to 36422
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Loan_Status                   36423 non-null  object
 1   Current_Loan_Amount           36423 non-null  int64
 2   Term                          36423 non-null  object
 3   Credit_Score                  36423 non-null  float64
 4   Annual_Income                 36423 non-null  float64
 5   Years_in_current_job          36423 non-null  object
 6   Home_Ownership                36423 non-null  object
 7   Purpose                       36423 non-null  object
 8   Monthly_Debt                  36423 non-null  float64
 9   Years_of_Credit_History       36423 non-null  float64
 10  Months_since_last_delinquent  36423 non-null  float64
 11  Number_of_Open_Accounts       36423 non-null  int64
 12  Number_of_Credit_Problems     36423 non-null  int64
 13  Current_Credit_Balance        36423 non-null  int64
 14  Maximum_Open_Credit           36423 non-null  float64
 15  Bankruptcies                  36423 non-null  float64
 16  Tax_Liens                     36423 non-null  float64
dtypes: float64(8), int64(4), object(5)
memory usage: 4.7+ MB

In [4]:
# Generate our categorical variable list
loans_cat = loans_df.dtypes[loans_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
loans_df[loans_cat].nunique()

Loan_Status              2
Term                     2
Years_in_current_job    11
Home_Ownership           4
Purpose                  7
dtype: int64

In [5]:
# Check the unique value counts to see if binning is required
loans_df.Years_in_current_job.value_counts()

10+_years    13149
2_years       3225
3_years       2997
<_1_year      2699
5_years       2487
4_years       2286
1_year        2247
6_years       2109
7_years       2082
8_years       1675
9_years       1467
Name: Years_in_current_job, dtype: int64

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(loans_df[loans_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(loans_cat)
encode_df.head()

,Loan_Status_Fully_Paid,Loan_Status_Not_Paid,Term_Long_Term,Term_Short_Term,Years_in_current_job_10+_years,Years_in_current_job_1_year,Years_in_current_job_2_years,Years_in_current_job_3_years,Years_in_current_job_4_years,Years_in_current_job_5_years,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [8]:
# Remove loan status target from features data
y = encode_df.Loan_Status_Fully_Paid
X = encode_df.drop(columns=["Loan_Status_Fully_Paid","Loan_Status_Not_Paid"])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.795

In [10]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 24
hidden_nodes_layer2 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
854/854 [==============================] - 1s 878us/step - loss: 0.5097 - accuracy: 0.7907
Epoch 2/50
854/854 [==============================] - 1s 985us/step - loss: 0.5000 - accuracy: 0.7954
Epoch 3/50
854/854 [==============================] - 1s 870us/step - loss: 0.4996 - accuracy: 0.7954
Epoch 4/50
854/854 [==============================] - 1s 976us/step - loss: 0.4990 - accuracy: 0.7955
Epoch 5/50
854/854 [==============================] - 1s 891us/step - loss: 0.4988 - accuracy: 0.7954
Epoch 6/50
854/854 [==============================] - 1s 934us/step - loss: 0.4986 - accuracy: 0.7955
Epoch 7/50
854/854 [==============================] - 1s 860us/step - loss: 0.4985 - accuracy: 0.7955
Epoch 8/50
854/854 [==============================] - 1s 898us/step - loss: 0.4981 - accuracy: 0.7955
Epoch 9/50
854/854 [==============================] - 1s 915us/step - loss: 0.4981 - accuracy: 0.7955
Epoch 10/50
854/854 [==============================] - 1s 870us/step - loss: 0.4978 - accuracy: 0.7955
Epoch 11/50
854/854 [==============================] - 1s 894us/step - loss: 0.4978 - accuracy: 0.7955
Epoch 12/50
854/854 [==============================] - 1s 941us/step - loss: 0.4977 - accuracy: 0.7956
Epoch 13/50
854/854 [==============================] - 1s 1ms/step - loss: 0.4976 - accuracy: 0.7958
Epoch 14/50
854/854 [==============================] - 1s 872us/step - loss: 0.4976 - accuracy: 0.7958
Epoch 15/50
854/854 [==============================] - 1s 912us/step - loss: 0.4971 - accuracy: 0.7957
Epoch 16/50
854/854 [==============================] - 1s 931us/step - loss: 0.4973 - accuracy: 0.7957
Epoch 17/50
854/854 [==============================] - 1s 915us/step - loss: 0.4971 - accuracy: 0.7957
Epoch 18/50
854/854 [==============================] - 1s 908us/step - loss: 0.4971 - accuracy: 0.7957
Epoch 19/50
854/854 [==============================] - 1s 907us/step - loss: 0.4969 - accuracy: 0.7957
Epoch 20/50
854/854 [==============================] - 1s 892us/step - loss: 0.4970 - accuracy: 0.7957
Epoch 21/50
854/854 [==============================] - 1s 884us/step - loss: 0.4970 - accuracy: 0.7957
Epoch 22/50
854/854 [==============================] - 1s 887us/step - loss: 0.4967 - accuracy: 0.7956
Epoch 23/50
854/854 [==============================] - 1s 855us/step - loss: 0.4967 - accuracy: 0.7960
Epoch 24/50
854/854 [==============================] - 1s 846us/step - loss: 0.4968 - accuracy: 0.7958
Epoch 25/50
854/854 [==============================] - 1s 888us/step - loss: 0.4966 - accuracy: 0.7960
Epoch 26/50
854/854 [==============================] - 1s 886us/step - loss: 0.4966 - accuracy: 0.7956
Epoch 27/50
854/854 [==============================] - 1s 931us/step - loss: 0.4962 - accuracy: 0.7958
Epoch 28/50
854/854 [==============================] - 1s 815us/step - loss: 0.4966 - accuracy: 0.7957
Epoch 29/50
854/854 [==============================] - 1s 863us/step - loss: 0.4964 - accuracy: 0.7959
Epoch 30/50
854/854 [==============================] - 1s 854us/step - loss: 0.4963 - accuracy: 0.7958
Epoch 31/50
854/854 [==============================] - 1s 895us/step - loss: 0.4961 - accuracy: 0.7958
Epoch 32/50
854/854 [==============================] - 1s 849us/step - loss: 0.4963 - accuracy: 0.7960
Epoch 33/50
854/854 [==============================] - 1s 848us/step - loss: 0.4961 - accuracy: 0.7957
Epoch 34/50
854/854 [==============================] - 1s 850us/step - loss: 0.4961 - accuracy: 0.7957
Epoch 35/50
854/854 [==============================] - 1s 852us/step - loss: 0.4960 - accuracy: 0.7957
Epoch 36/50
854/854 [==============================] - 1s 860us/step - loss: 0.4958 - accuracy: 0.7957
Epoch 37/50
854/854 [==============================] - 1s 858us/step - loss: 0.4959 - accuracy: 0.7960
Epoch 38/50
854/854 [==============================] - 1s 872us/step - loss: 0.4959 - accuracy: 0.7957
Epoch 39/50
854/854 [==============================] - 1s 849us/step - loss: 0.4959 - accuracy: 0.7958
Epoch 40/50
854/854 [==============================] - 1s 880us/step - loss: 0.4959 - accuracy: 0.7956
Epoch 41/50
854/854 [==============================] - 1s 879us/step - loss: 0.4957 - accuracy: 0.7956
Epoch 42/50
854/854 [==============================] - 1s 843us/step - loss: 0.4957 - accuracy: 0.7956
Epoch 43/50
854/854 [==============================] - 1s 862us/step - loss: 0.4955 - accuracy: 0.7959
Epoch 44/50
854/854 [==============================] - 1s 913us/step - loss: 0.4957 - accuracy: 0.7960
Epoch 45/50
854/854 [==============================] - 1s 857us/step - loss: 0.4954 - accuracy: 0.7961
Epoch 46/50
854/854 [==============================] - 1s 885us/step - loss: 0.4957 - accuracy: 0.7960
Epoch 47/50
854/854 [==============================] - 1s 852us/step - loss: 0.4955 - accuracy: 0.7961
Epoch 48/50
854/854 [==============================] - 1s 854us/step - loss: 0.4955 - accuracy: 0.7958
Epoch 49/50
854/854 [==============================] - 1s 854us/step - loss: 0.4956 - accuracy: 0.7958
Epoch 50/50
854/854 [==============================] - 1s 840us/step - loss: 0.4955 - accuracy: 0.7962
285/285 - 0s - loss: 0.5000 - accuracy: 0.7957 - 268ms/epoch - 942us/step
Loss: 0.5000474452972412, Accuracy: 0.7957390546798706